name: Push Code

on:
  push:
    branches:
      - main  # or any branch you want to trigger this action

jobs:
  push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        
    - name: Make changes
      run: |
        # Add your commands here to make changes to your code
        # For example:
        # echo "Hello, World!" > hello.txt
        
    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Automated push: Update files" || echo "No changes to commit"
        git push
